config/routes.rb
Rails.application.routes.draw do

  get 'about/index'

  get     'sessions/new'
  root    'home#index'
  get     'staff_section/index', as: 'staff_section'
  get     'student_section/index', as: 'student_section'
  get     'student'               => 'student_section#index'
  get     'faculty'               => 'staff_section#index'
  get     'home/about',           as: 'about'
  get     'departments/cse'
  get     'departments/ece'
  get     'departments/civil'
  get     'departments/mech'
  get     'departments/ee'
  get     'departments/hum'
  get     'users/show'
  get     'signup'       => 'users#new'
  get     'login'                => 'sessions#new'
  post    'login'                 => 'sessions#create'
  delete  'logout'                => 'sessions#destroy'
  resources :users
  resources :assignments
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  mount_uploader :articleimage, ArticleImageUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: {minimum: 10}
  validates :content, presence: true, length: {minimum: 100}
  validates :post_type, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :logged_in_user, only: [:new, :edit, :update, :destroy]

  def index
    @user = current_user
    @articles = Article.paginate(page: params[:page])
  end

  def new
    @article = Article.new
  end

  def show
    @user = current_user
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article Created"
      redirect_to :back
    else
      flash[:error] = "Article creation Failed"
      redirect_to :back
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update_attributes(article_params)
      flash[:success] = "Article Updated"
      redirect_to current_user
    else
      flash[:error] = "Error Updating Article"
      render 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "Article Deleted"
    redirect_to :back
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :post_type, :articleimage, :approved)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/views/articles/_article.html.erb
<div class="row">
  <div class="two wide column">
    <% if !article.articleimage.file.nil? %>
    <div class="ui small image">
      <img src="<%= article.articleimage.url %>"/>
    </div>
    <% end %>
  </div>

    <div class="four wide column">
      <h3 style="font-weight: lighter;"><%= article.title %></h3>
      <h4 style="font-weight: lighter;"><%= truncate(article.content, length: 200, omission: '... (continued)') %></h4>
    </div>
    <div class="three wide column">
      <h5 style="font-weight: lighter;"> Category: <%= article.post_type %></h5>
      <h5 style="font-weight: lighter;">Uploaded <%= time_ago_in_words(article.created_at) %> ago.</h5>
    </div>
  <div class="four wide column">
    <div class="ui buttons">
      <%= link_to "Show", article, class: "ui blue button" %>
      <% if current_user?(article.user) %>
      <%= link_to "Edit", edit_article_path(article), class: "ui red button" %>
      <%= link_to "Delete",article_path(article), method: :delete, class: "ui violet button" %>
      <% end %>
    </div>
  </div>
  <div class="three wide column">
    <%= form_for(article) do |f| %>
    <div class="ui disabled toggle checkbox">
      <%= f.check_box :approved, class: "ui checkbox", disabled: "disabled" %>
      <label>Verified?</label>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<% provide(:title, truncate("Editing")) %>

<div id="spacer" class="massive ui menu">
  &nbsp;
</div>

<%= form_for(@article, html: {class: "ui form article", multipart: true, style: "margin-bottom: 10%;"}) do |f| %>
<div class="row wrap">
  <div class="ui error message"></div>
  <div class="two fields">
    <div class="required field">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: "Enter title of Assignment" %>
    </div>
    <div class="required field">
      <%= f.label :post_type %>
      <%= f.select(:post_type, ["News", "Blog", "Research", "Statements"], {}, {}) %>
    </div>
  </div>

  <div class="required field">
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: "Enter content of Assignment" %>
  </div>

  <% if current_user.admin? || admin?(current_user) %>
  <div class="required field">
    <div class="ui toggle checkbox">
      <%= f.check_box :approved, class: "ui checkbox" %>
      <label>Verified?</label>
    </div>
  </div>
  <% end %>

  <%= f.submit "Update Article!", class: "ui green button" %>
  <%= f.file_field :articleimage %>
</div>

<% end %>

app/views/articles/index.html.erb
<div id="spacer" class="massive ui menu">
  &nbsp;
</div>

<% if @articles.any? %>
<div class="ui centered cards">
  <% @articles.each do |article| %>
  <div class="card">
    <% if !article.articleimage.file.nil? %>
    <div class="image">
      <img src="<%= article.articleimage.url %>"/>
    </div>
    <% end %>
    <div class="content">
      <a class="header" href="<%= article_path(article) %>"><%=article.title%></a>
      <div class="meta">A <%=article.post_type %> by <%= article.user.name %></div>
      <div class="description">
        <%= truncate(article.content, length: 100) %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/articles/show.html.erb
<% provide(:title, truncate(@article.title)) %>

<% if @article.articleimage.file.nil? %>
<div class="article-hero">
<% else %>
<div class="article-hero" style="background-image: url(<%= @article.articleimage.url %>)">
<% end %>
  <div class="article-hero-header">
    <h1 class="wow fadeInLeft"><%= @article.title %></h1>
    <% if @article.post_type == "Blog" %>
    <h2 class="wow fadeInRight">A Blog by <%= @article.user.name %></h2>
    <% end %>
    <h3 class="wow fadeInUp">Published: <%= @article.created_at.strftime("%A, %B %d %Y") %></h3>
  </div>
</div>

<div class="article-content">
  <p>
    <%= simple_format(@article.content) %>
  </p>
</div>