config/routes.rb
Rails.application.routes.draw do

  get 'about/index'

  get     'sessions/new'
  root    'home#index'
  get     'staff_section/index', as: 'staff_section'
  get     'student_section/index', as: 'student_section'
  get     'student'               => 'student_section#index'
  get     'faculty'               => 'staff_section#index'
  get     'home/about',           as: 'about'
  get     'departments/cse'
  get     'departments/ece'
  get     'departments/civil'
  get     'departments/mech'
  get     'departments/ee'
  get     'departments/hum'
  get     'users/show'
  get     'signup'       => 'users#new'
  get     'login'                => 'sessions#new'
  post    'login'                 => 'sessions#create'
  delete  'logout'                => 'sessions#destroy'
  resources :users
  resources :assignments
  resources :articles

end

app/models/user.rb
class User < ActiveRecord::Base

  extend FriendlyId
  friendly_id :rollno, use: :slugged
  validates :rollno, :slug, presence: true

  has_many :assignments, dependent: :destroy
  has_many :articles, dependent: :destroy
  attr_accessor :remember_token
  before_save{self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+.\-]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 256},
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }

  validates :name, presence: true, length: {maximum: 50}

  VALID_ROLLNO_REGEX = /\A[0-9]+\z/
  validates :rollno, presence: true, length: {maximum: 20},
  format: { with: VALID_ROLLNO_REGEX }, uniqueness: true

  validates :branch, presence: true
  validates :user_type, presence: true

  has_secure_password
  validates :password, length: {minimum: 8}, allow_blank: true

#Returns hash digest of given password
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

#Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

#Remembers a user in database
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

#Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

#Returns true if given token matches digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :destroy, :new]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy, :new]

  def index
    @user = current_user
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.friendly.find(params[:id])
    @assignments = @user.assignments.paginate(page: params[:page])
    @assignment = current_user.assignments.build if logged_in?
    @article = current_user.articles.build if logged_in?
    @articles = @user.articles.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User Created!"
      render 'new'
      #log_in @user
      #redirect_to @user
    else
      flash[:error] = "User not created"
      render 'new'
    end
    @user = current_user
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.friendly.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :rollno, :email, :admin, :phone_number, :user_type, :branch, :password, :password_confirmation, :other_designations)
  end

  #Before Filters


#Confirms if user is correct
  def correct_user
    @user = User.friendly.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || current_user.admin? || admin?(current_user)
  end

  #Confirms admin_user
  def admin_user
    redirect_to(root_url) unless current_user.admin? || admin?(current_user)
  end

  def faculty_user
    redirect_to(root_url) unless current_user.user_type == 'Faculty'
  end

end

app/helpers/users_helper.rb
module UsersHelper

  #Returns gravatar images for user emails
  def gravatar_for(user, options={size: 120})
    if !user.email.nil?
      gravatar_id = Digest::MD5::hexdigest(user.email)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")    
    end
  end

  #Returns gravatar images url
  def gravatar_url(user, options={size:120})
    if !user.email.nil?
      gravatar_id = Digest::MD5::hexdigest(user.email)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      gravatar_url
    end
  end
end

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>

<div id="spacer" class="massive ui menu">
  &nbsp;
</div>

<div class="ui grid container">
  <div class="six wide centered column">
    <h1 style="text-align: center;">Update your Profile</h1>
    <%= form_for(@user, html: {class: "ui form"}) do |f| %>

    <%= render 'shared/error_messages' %>
    <div class="field" style="text-align: center">
      <%= gravatar_for @user %>
    </div>
    <div class="field" style="text-align: center">
      <a href="http://gravatar.com/emails" target="_blank"
      class="ui teal button">Change Profile Picture</a>
    </div>

    <% if current_user.admin? || admin?(current_user) %>
    <div class="field">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, placeholder: "Full Name as stated in records" %>
    </div>

    <div class="field">
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, type: "email" %>
    </div>

    <div class="field">
      <%= f.label :rollno, "Roll No/Emp. No"%>
      <%= f.text_field :rollno, type: "number", placeholder: "Provided by Institute" %>
    </div>

    <div class="field">
      <%= f.label :phone_number, "Phone Number"%>
      <%= f.text_field :phone_number, placeholder: "User's available mobile number" %>
    </div>

    <div class="field">
      <%= f.label :user_type %>
      <%= f.select(:user_type, ["Student", "Faculty", "Staff", "Director"], {}, {}) %>
    </div>

    <div class="field">
      <%= f.label :branch %>
      <%= f.select(:branch, ["Civil", "Mechanical", "Electrical", "Computer Science", "Electronics"], {}, {}) %>
    </div>

    <div class="field">
      <%= f.label :other_designations, "Other Designations" %>
      <%= f.text_field :other_designations, placeholder: "e.g. Exam Controller, Hostel Incharge" %>
    </div>

    <div class="field">
      <%= f.label :admin, "Admin?" %>
      <%= f.check_box :admin%>
    </div>

    <% else %>

    <div class="disabled field">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, placeholder: "Full Name as stated in records" %>
    </div>

    <div class="disabled field">
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, type: "email" %>
    </div>

    <div class="disabled field">
      <%= f.label :rollno, "Roll No/Emp. No"%>
      <%= f.text_field :rollno, type: "number", placeholder: "Roll No/Emp. No" %>
    </div>

    <div class="field">
      <%= f.label :phone_number, "Phone Number"%>
      <%= f.text_field :phone_number, placeholder: "User's available mobile number" %>
    </div>

    <div class="disabled field">
      <%= f.label :user_type %>
      <%= f.select(:user_type, ["Student", "Faculty"], {}, {}) %>
    </div>

    <div class="disabled field">
      <%= f.label :branch %>
      <%= f.select(:branch, ["Civil", "Mechanical", "Electrical", "Computer Science", "Electronics"], {}, {}) %>
    </div>

    <div class="disabled field">
      <%= f.label :other_designations, "Other Designations" %>
      <%= f.text_field :other_designations, placeholder: "e.g. Exam Controller, Hostel Incharge" %>
    </div>
    <% end %>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, type: "password"%>
    </div>

    <div class="field">
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, type: "password" %>
    </div>

    <div class="field" style="text-align: center;">
      <%= f.submit "Update Profile", class: "ui blue button" %>
    </div>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<div id="spacer" class="massive ui menu">
  &nbsp;
</div>
<div class="ui grid container centered">
  <a href="<%= signup_path %>" class="ui pink button" style= "margin: 5%;">Create A User!</a>
  <div class="ui row">
    <%= will_paginate @users, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
  </div>
  <% @users.each do |user| %>
  <div class="ui row">
    <div class="one wide column">
      <%= gravatar_for user, size: 60 %>
    </div>
    <div class="three wide column">
      <h4><%= user.name %></h4>
    </div>
    <% if current_user.admin? || admin?(current_user) && !current_user?(user) %>
    <div class="four wide column">
      <div class="ui buttons">
        <%= link_to "Show Profile", user, class:"ui blue button"  %>
        | <%= link_to "Edit Profile", edit_user_path(user), class: "ui orange button" %>
        | <%= link_to "Delete User", user, method: :delete, data: {confirm: "Are you sure?"}, class: "ui red button" %>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
  <%= will_paginate @users, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign-up') %>

<div id="spacer" class="massive ui menu">
  &nbsp;
</div>

<div class="ui grid container">
  <div class="six wide centered column">
    <h1 style="text-align: center;">Add A User</h1>
    <%= form_for(@user, html: {class: "ui form"}) do |f| %>

    <%= render 'shared/error_messages' %>
    <div class="field">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, placeholder: "Full Name as stated in records" %>
    </div>

    <div class="field">
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, type: "email", placeholder: "If not available then ask the student/staff to provide one" %>
    </div>

    <div class="field">
      <%= f.label :rollno, "Roll No/Emp. No"%>
      <%= f.text_field :rollno, type: "number", placeholder: "Provided by Institute" %>
    </div>

    <div class="field">
      <%= f.label :phone_number, "Phone Number"%>
      <%= f.text_field :phone_number, placeholder: "User's available mobile number" %>
    </div>

    <div class="field">
      <%= f.label :user_type %>
      <%= f.select(:user_type, ["Student", "Faculty", "Staff", "Director"], {}, {}) %>
    </div>

    <div class="field">
      <%= f.label :branch %>
      <%= f.select(:branch, ["Civil", "Mechanical", "Electrical", "Computer Science", "Electronics"], {}, {}) %>
    </div>

    <div class="field">
      <%= f.label :other_designations, "Other Designations" %>
      <%= f.text_field :other_designations, placeholder: "e.g. Exam Controller, Hostel Incharge" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, type: "password"%>
    </div>

    <div class="field">
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, type: "password" %>
    </div>

    <div class="field" style="text-align: center;">
      <%= f.submit "Add User to Database!", class: "ui blue button" %>
    </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div id="spacer" class="massive ui menu">
  &nbsp;
</div>

<div class="hero-user" style="margin-top: 50px;">
  <div class="ui two column grid container stackable">
    <div class="column">
      <div class="ui grid">
        <div class="six wide column" >
          <%= gravatar_for @user %>
        </div>
        <div class="ten wide column user-details" data-intro="These are your personal records"
        data-step="1">
          <h2><%= @user.name %></h2>
          <h3><%= @user.branch %> <%= @user.user_type %></h3>
          <h4><%= @user.rollno %></h4>
          <% if @user.admin? || admin?(@user) %>
          <h4>+91(<%= @user.phone_number %>)</h4>
          <% end %>
        </div>
      </div>
    </div>
    <div class="middle aligned column stackable">
      <div class="ui buttons">
        <% if !current_user.nil? %>
        <% if current_user.admin? || current_user?(@user) || admin?(current_user) %>
        <a href="<%= edit_user_path %>" class="ui orange button">Edit Profile</a>
        <% end %>
        <% if current_user?(@user) %>
        <button id="submit-assignment-button" class="ui green button">Submit Assignment</button>
        <button id="submit-article-button" class="ui violet button">Submit Article</button>
        <%= link_to "Logout", logout_path, method: 'delete', class: "ui grey button" %>
        <% end %>
      </div>
      <% if current_user.admin? || admin?(current_user) %>
      <%= link_to "Users Management",users_path, class:"ui black button" %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="tabs-user">
  <div class="ui top attached tabular menu stackable">
    <a class="item active teal" data-tab="articles" data-intro="Here is the list of your submitted articles"
    data-step="3">Articles
      <span class="ui left pointing teal label"><%= @user.articles.count %></span>
    </a>
    <% if !current_user.nil? %>
    <a class="teal item" data-tab="assignments" data-intro="Here is the list of your submitted assignments"
    data-step="4">Assignments
      <span class="ui teal left pointing label"><%= @user.assignments.count %></span>
    </a>
    <a class="teal item" data-tab="submit_assignment" data-intro="You can submit assignments from here"
    data-step="5">Submit Assignment</a>
    <a class="teal item" data-tab="submit_article" data-intro="You can submit articles from here"
    data-step="6">Submit Article</a>
    <% end %>
  </div>

  <!-- Show User's Articles Page -->
  <div class="ui bottom attached tab segment active" data-tab="articles">
    <% if @user.articles.any? %>
    <div class="ui three column middle aligned centered grid stackable">
      <%= render @articles %>
    </div>
    <%= will_paginate @articles, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
    <% end %>
  </div>

  <% if !current_user.nil? %>
    <!-- Show User's Assignments Page -->
    <div class="ui bottom attached tab segment" data-tab="assignments">
      <% if @user.assignments.any? %>
      <div class="ui three column middle aligned centered grid stackable">
        <%= render @assignments %>
      </div>
      <%= will_paginate @assignments, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
      <% end %>
    </div>
  <% end %>

<% if !current_user.nil? %>
  <!-- Submit Assignment Form -->

  <div class="ui bottom attached tab segment" data-tab="submit_assignment">
    <%= form_for(@assignment, html: {class: "ui form assignment", multipart: true}) do |f| %>
    <div class="ui error message"></div>
    <div class="three fields">
      <div class="required field">
        <%= f.label "Title" %>
        <%= f.text_field :title, placeholder: "Title of Assignment" %>
      </div>

      <div class="required field">
        <%= f.label :subject %>
        <%= f.text_field :subject, placeholder: "Subject of Assignment" %>
      </div>
      <div class="required field">
        <%= f.label :semester %>
        <%= f.text_field :semester, type: "number",
        placeholder: "Enter your current semester" %>
      </div>
    </div>
    <%= f.submit "Upload", class: "ui teal button" %>
    <%= f.file_field :pdf %>

    <% end %>
  </div>

  <!-- Submit Article Tab -->

  <div class="ui bottom attached tab segment" data-tab="submit_article">
    <%= form_for(@article, html: {class: "ui form article", multipart: true}) do |f| %>
    <div class="row wrap">
      <div class="ui error message"></div>
      <div class="two fields">
        <div class="required field">
          <%= f.label :title %>
          <%= f.text_field :title, placeholder: "Enter title of Article" %>
        </div>
        <div class="required field">
          <%= f.label :post_type %>
          <%= f.select(:post_type, ["News", "Blog", "Research", "Statements"], {}, {}) %>
        </div>
      </div>

      <div class="required field">
        <%= f.label :content %>
        <%= f.text_area :content, placeholder: "Enter content of Article" %>
      </div>

      <% if current_user.admin? || admin?(current_user) %>
      <div class="required field">
        <%= f.label "Approved?" %>
        <%= f.check_box :approved%>
      </div>
      <% end %>

      <%= f.submit "Create!", class: "ui green button" %>
      <%= f.file_field :articleimage %>
    </div>

    <% end %>
  </div>
  <% end %>
</div>