config/routes.rb
Rails.application.routes.draw do

  get 'about/index'

  get     'sessions/new'
  root    'home#index'
  get     'staff_section/index', as: 'staff_section'
  get     'student_section/index', as: 'student_section'
  get     'student'               => 'student_section#index'
  get     'faculty'               => 'staff_section#index'
  get     'home/about',           as: 'about'
  get     'departments/cse'
  get     'departments/ece'
  get     'departments/civil'
  get     'departments/mech'
  get     'departments/ee'
  get     'departments/hum'
  get     'users/show'
  get     'signup'       => 'users#new'
  get     'login'                => 'sessions#new'
  post    'login'                 => 'sessions#create'
  delete  'logout'                => 'sessions#destroy'
  resources :users
  resources :assignments
  resources :articles

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user    
    @articles = Article.paginate(page: params[:page])
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer id="footer" class="footer">
  <div class="ui grid stackable container">

    <!-- Social -->
    <div class="centered row">
      <button class="ui circular facebook icon button">
        <i class="facebook icon"></i>
      </button>
      <button class="ui circular twitter icon button">
        <i class="twitter icon"></i>
      </button>
      <button class="ui circular linkedin icon button">
        <i class="linkedin icon"></i>
      </button>
      <button class="ui circular google plus icon button">
        <i class="google plus icon"></i>
      </button>
    </div>

    <!--Statistics -->
    <div class="centered row">
      <div class="ui inverted statistics">
        <div class="statistic">
          <div class="value">
            <%= developer_count.to_words %>
          </div>
          <div class="label">Developers</div>
        </div>

        <div class="statistic">
          <div class="value">
            <img src="/assets/user.jpg" class="ui circular inline image">
            <%= users_count %>
          </div>
          <div class="label">
            Users
          </div>
        </div>
        <div class="statistic">
          <div class="value">
            <%= number_with_delimiter(articles_count, delimiter: ',') %>
          </div>
          <div class="label">
            Articles Written
          </div>
        </div>
        <div class="statistic">
          <div class="value">
            <%= number_with_delimiter(assignments_count, delimiter: ',') %>
          </div>
          <div class="label">
            Assignments Submitted
          </div>
        </div>
        <div class="statistic">
          <div class="text value">
            HTML, CSS </br>
            Ruby, JS
          </div>
          <div class="label">
            Languages Used
          </div>
        </div>
      </div>
    </div>

    <!-- Links -->
    <div class="centered row">
      <div class="ui large borderless inverted menu">
        <div class="header active item">Useful Links:</div>
        <a href="http://uktech.ac.in" class="active item">
          UTU
        </a>
        <a class="active item">
          AICTE
        </a>
        <a class="active item">
          IIT
        </a>
        <a href="http://kecua.ac.in" class="active item">
          KEC
        </a>
        <a href="http://gbpec.ac.in" class="active item">
          GBPEC
        </a>
      </div>
    </div>
  </div>

</footer>

app/views/home/_navigation.html.erb
<div class="overlay">
  <div class="ui secondary menu large fixed">
    <a class="item menu-button">
      <i class="sidebar icon"></i>
    </a>
    <div id="menu-search" class="ui icon input" >
      <input type="text" placeholder="Search...">
      <i class="search icon"></i>
    </div>
    <div class="right menu">
      <a class="item" href="<%= student_path %>" id="my-content">For Students</a>
      <a class="item" href="<%= faculty_path %>"id="my-content">For Faculty</a>
      <% if logged_in? %>
      <%= link_to current_user, class: 'item' do %>
        <% if !current_user.email.nil? %>
        <img class="ui avatar image" src="<%= gravatar_url current_user %>">
        <span><%= current_user.name %></span>
        <% elsif !@user.email.nil? %>
        <img class="ui avatar image" src="<%= gravatar_url @user %>">
        <span><%= @user.name %></span>
        <% end %>
      <% end %>
      <% else %>
      <div class="item">
        <a href="<%= signup_path %>" class="ui labeled icon green button">
          <i class="sign in icon"></i>
          Login
        </a>
      </div>
      <% end %>
      <a class="item" href="javascript:void(0);" onclick="javascript:introJs().start();javascript:introJs().addHints();">
        <i class="help large circle icon"></i>Help
      </a>
    </div>
  </div>
</div>

app/views/home/_sidebar.html.erb
<div class="ui sidebar vertical menu">
  <div id="menu-search1" class="ui icon input" >
    <input type="text" placeholder="Search...">
    <i class="search icon"></i>
  </div>
  <div>
    <i class="home icon" id="homeicon"></i>
    <a  class="item" href="<%= root_path %>" id="home">
      Home
    </a>
  </div>

  <div>
    <div>
      <i class="student icon" id="homeicon"></i>
      <a class="item" id="my-conten1" href="<%= student_path %>">
        Student Section
      </a>
    </div>

    <div>
      <i class="spy icon" id="homeicon"></i>
      <a  class="item" id="my-conten1" href="<%= faculty_path %>">
        Faculty section
      </a>
    </div>

    <i class="sign in icon" id="homeicon"></i>
    <a class="item" href="<%= login_path %>">
      Login
    </a>
  </div>
  <div>
    <i class="info icon" id="homeicon"></i>
    <div class="item">
      <div class="header">About</div>
      <div class="menu">
        <a class="item">About ITG</a>
        <a class="item">About UTU</a>
        <a class="item">Vice Chancellor's Message</a>
        <a class="item">Director's Message</a>
      </div>
    </div>
  </div>
  <div>
    <i class="book icon" id="homeicon"></i>

    <div class="item">
      <div class="header">Academics</div>
      <div class="menu">
        <a class="item" href="<%=student_path %>#/programmes">Programmes</a>
        <a class="item" href="<%=student_path %>#/fees">Fees Structure</a>
        <a class="item" href="<%= student_path %>#/facilities">Facilities</a>
      </div>
    </div>
  </div>
  <div>
    <i class="university icon" id="homeicon"></i>

    <div class="item">
      <div class="header">Administration</div>
      <div class="menu">
        <a class="item" href="<%= faculty_path %>#/administration">Vice-Chancellor</a>
        <a class="item" href="<%= faculty_path %>#/administration">Director</a>
        <a class="item" href="<%= faculty_path %>#/faculty-incharges">Faculty Incharges</a>
      </div>
    </div>
  </div>
  <div>

    <i class="building outline icon" id="homeicon"></i>
    <div class="item">
      <div class="header">Departments</div>
      <div class="menu">
        <a class="item" href="<%= departments_cse_path %>">Computer Science Engineering</a>
        <a class="item" href="<%= departments_civil_path %>">Civil Engineering</a>
        <a class="item" href="<%= departments_ee_path %>">Electrical Engineering</a>
        <a class="item" href="<%= departments_ece_path %>">Electronics & Communication Engineering</a>
        <a class="item" href="<%= departments_mech_path %>">Mechanical Engineering</a>
        <a class="item" href="<%= departments_hum_path %>">Applied Science & Humanities</a>
      </div>
    </div>
  </div>

  <div>
    <i class="call icon" id="homeicon"></i>
    <a class="item">
      Contact
    </a>
  </div>
</div>

app/views/home/about.html.erb
<% provide(:title, "About") %>

<!DOCTYPE html>
<html class="no-js" dir="ltr" lang="en">
<body>

</body>
</html>

app/views/home/index.html.erb
<% provide(:title, "Home") %>

<!DOCTYPE html>
<html class="no-js" dir="ltr" lang="en">

<body>
	<!--HERO SECTION-->
	<section class="hero">
		<div class="hero-content">
			<h1 class="wow fadeInLeft">Institute Of Technology, Gopeshwar</h1>
			<h4 class="wow fadeInRight">The youngest constituent college of UTU</h4>
			<a href="#" id="learnmore">
				<i class="fa fa-chevron-circle-down animated flash"></i>
			</a>
		</div>
	</section>


	<!--MAIN SECTION-->
	<section class="main-body">
		<div class="large-window1 lazy">
			<div class="window1-tint">
				<div class="window1-text wow bounceInLeft">
					<p>
						First
						<strong>Text here</strong>
					</p>
					<button class="ui brown button">Call To Action</button>
				</div>
			</div>
		</div>
		<div class="large-window2 lazy">
			<div class="window2-tint">
				<div class="window2-text wow flipInX">
					<p>
						Second
						<strong>Text here</strong>
					</p>
					<button class="ui red button">Call To Action</button>
				</div>
			</div>
		</div>

		<div class="large-window3 lazy">
			<div class="window3-tint">
				<div class="window3-text wow flipInY">
					<p>
						Third
						<strong>Text here</strong>
					</p>
					<button class="ui green button">Call To Action</button>
				</div>
			</div>
		</div>

		<div class="large-window4 lazy">
			<div class="window4-tint">
				<div class="window4-text wow lightSpeedIn">
					<p>
						Forth
						<strong>Text here</strong>
					</p>
					<button class="ui white button">Call To Action</button>
				</div>
			</div>
		</div>
	</section>

</body>
<script>
//Lazy-Load
$('section.lazy').lazyload({
	effect: "fadeIn"
});
</script>
</html>